server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/
    #是否将自己注册到 Eureka Server，默认为 true，由于当前就是 server，故而设置成 false
    register-with-eureka: false
    #是否从 eureka server 获取注册信息，由于单节点，不需要同步其他节点数据，故而设置成 false
    fetch-registry: false
  server:
    #关闭自我保护
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080