eureka:
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/
server:
  port: 8081
  application:
    name: consumer
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule