eureka:
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/
spring:
#  #zipkin
#  zipkin:
#    base-url: http://localhost:9411/
#    #采样比例1
#  sleuth:
#    sampler:
#      rate: 1
  application:
    name: user-provider
server:
  port: 8091

---
server:
  port: 8091
spring:
  profiles: 8091
---
server:
  port: 8092
spring:
  profiles: 8092